// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzYXU4E9NLsnEXaCkn8meKKwC7A0lpeQw',
    appId: '1:668321299361:web:c8f0f260fb684f1b5829e0',
    messagingSenderId: '668321299361',
    projectId: 'mobileproject-44f18',
    authDomain: 'mobileproject-44f18.firebaseapp.com',
    storageBucket: 'mobileproject-44f18.appspot.com',
    measurementId: 'G-S9E2G5LE8C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdxMbzI4dYn-PJc1sOjKsRLJOv5R0U7Rs',
    appId: '1:668321299361:android:9201718cb42934af5829e0',
    messagingSenderId: '668321299361',
    projectId: 'mobileproject-44f18',
    storageBucket: 'mobileproject-44f18.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjiDGfxs_rhqjE5zl-_d7H-QKkAQsMlQk',
    appId: '1:668321299361:ios:2e3de9c7ea601fc55829e0',
    messagingSenderId: '668321299361',
    projectId: 'mobileproject-44f18',
    storageBucket: 'mobileproject-44f18.appspot.com',
    iosBundleId: 'com.example.hope',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjiDGfxs_rhqjE5zl-_d7H-QKkAQsMlQk',
    appId: '1:668321299361:ios:fd47af784597ecda5829e0',
    messagingSenderId: '668321299361',
    projectId: 'mobileproject-44f18',
    storageBucket: 'mobileproject-44f18.appspot.com',
    iosBundleId: 'com.example.hope.RunnerTests',
  );
}
